config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do
   resources :products
   resources :orders do
     member do
       post :cancel
       post :ship
       post :shipped
       post :return
     end
   end
  end

  resources :favorites

  resources :products do
    member do
      post :add_to_cart
      post :favorite
      post :unfavorite
    end
    collection do
     get :search
     get :fresh
     get :food
     get :men
     get :women
     get :beautiful
     get :glasses
     get :luggage
     get :furniture
   end
   resources :reviews
  end

  resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

   resources :cart_items do
     member do
       post :add_quantity
       post :remove_quantity
     end
   end

   resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

   namespace :account do
     resources :users
     resources :orders
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
     ci = cart_items.build
     ci.product = product
     ci.quantity = 1
     ci.save
   end

   def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

  def clean!
   cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  has_many :product_lists

  def set_payment_with!(method)
     self.update_columns(payment_method: method )
   end

   def pay!
     self.update_columns(is_paid: true )
   end

   include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned


    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid,         to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :reviews, dependent: :destroy
  has_many :favorites
  has_many :fans, :through => :favorites, :source => :user
  belongs_to :category

  has_many :photos
  accepts_nested_attributes_for :photos
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/review.rb
class Review < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    is_admin
  end

  has_many :orders
  has_many :reviews, dependent: :destroy
  has_many :favorites
  has_many :favorite_products, :through => :favorites, :source => :product

  def is_fan_of?(group)
    favorite_products.include?(group)
  end 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clean
    current_cart.clean!
    flash[:warning] = "已清空购物车"
    redirect_to carts_path
  end

  def checkout
    @order = Order.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total = current_cart.total_price

    if @order.save

      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order = @order
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.quantity = cart_item.quantity
        product_list.save
      end
      current_cart.clean!
      OrderMailer.notify_order_placed(@order).deliver!

      redirect_to order_path(@order.token)
    else
      render 'carts/checkout'
    end
  end

  def show
    @order = Order.find_by_token(params[:id])
    @product_lists = @order.product_lists
  end

  def pay_with_alipay
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("alipay")
    @order.pay!
    @order.make_payment!

    redirect_to order_path(@order.token), notice: "使用支付宝成功完成付款"
  end

  def pay_with_wechat
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("wechat")
    @order.pay!
    @order.make_payment!

    redirect_to order_path(@order.token), notice: "使用微信成功完成付款"
  end

  def apply_to_cancel
    @order = Order.find_by_token(params[:id])
    OrderMailer.apply_cancel(@order).deliver!
    flash[:notice] = "已提交申请"
    redirect_back fallback_location: root_path
  end

  private

  def order_params
    params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to product_path(@product), notice: '评论成功'
    else
      redirect_to product_path(@product), notice: '请输入您的评论'
    end
  end

    def destroy
      @product = Product.find(params[:product_id])
      @review = Review.find(params[:id])
      @review.destroy
      redirect_to product_path(@product), alert: "成功删除评论内容。"
    end

  private

  def review_params
    params.require(:review).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
   :user
 end

 def resource
     @resource ||= User.new
 end

 def resource_class
     User
 end

 def devise_mapping
     @devise_mapping ||= Devise.mappings[:user]
 end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
     cart.total_price
   end 
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_paid_state(order)
   if order.is_paid?
     "已付款"
   else
     "未付款"
   end
 end
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_highlight_content(product,query_string)
   excerpt_cont = excerpt(product.title, query_string, radius: 500)
   highlight(excerpt_cont, query_string)
 end

 def render_active(index)
  if index == 0
    "active"
  end
end 
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/checkout.html.erb
<div class="row">
   <div class="col-md-6 col-md-offset-3">

    <h2 class="text-center"> 购物明细 </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">商品明细</th>
          <th>单价</th>
          <th>数量</th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
            </td>
            <td>
              <%= cart_item.product.price %>
            </td>

            <td>
              <%= cart_item.quantity %>
            </td>

          </tr>
        <% end %>

      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        总计<%= render_cart_total_price(current_cart) %>元
      </span>
    </div>

    <hr>

    <h2 class="text-center"> 订单资讯 </h2>

    <div class="order-form">

      <%= simple_form_for @order do |f| %>
          <legend> 订购人</legend>
          <div class="form-group col-lg-4">
            <%= f.input :billing_name, label: "订购人"   %>
          </div>
          <div class="form-group col-lg-8">
            <%= f.input :billing_address, label: "地址" %>
          </div>

          <legend> 收货人</legend>
          <div class="form-group col-lg-4">
           <%= f.input :shipping_name, label: "收货人"  %>
          </div>
          <div class="form-group col-lg-8">
            <%= f.input :shipping_address, label: "地址"  %>
          </div>

        <div class="checkout">
          <%= f.submit "生成订单", class: "btn btn-lg btn-danger pull-right",
                       data: { disable_with: "Submitting..." } %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/carts/index.html.erb
  <div class="col-md-7 col-centered">
    <%= link_to("清空购物车", clean_carts_path,
      method: :delete, class: "btn btn-warning pull-right",
      data: { confirm: "你确定要清空整个购物车吗？"})%>
    <h2>我的购物车</h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">商品咨询</th>
          <th>单价</th>
          <th>数量</th>
          <th>操作选项</th>
        </tr>
      </thead>

      <tbody>
        <% current_cart.cart_items.each do |cart_item| %>
        <tr>
          <td>
              <%= link_to product_path(cart_item.product) do %>
                <% if cart_item.product.photos[0].present? %>
                  <%= image_tag(cart_item.product.photos[0].avatar.thumb.url, class: "thumbnail") %>
                <% else %>
                  <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
            </td>
            <td>
              <%= cart_item.product.price %>
            </td>
            <td>
              <div class="count-input">
               <%= link_to("-", remove_quantity_cart_item_path(cart_item.product_id), class: "incr-btn", method: :post) %>
               <input class="quantity" type="text" value="<%= cart_item.quantity %>">
               <%= link_to("+", add_quantity_cart_item_path(cart_item.product_id), class: "incr-btn", method: :post) %>
             </div>
            </td>
            <td>
              <%= link_to cart_item_path(cart_item.product_id), method: :delete do %>
              <i class="fa fa-trash"></i>
              <% end %>
            </td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <div class="total clearfix">
      <span class="pull-right">
        <span>
          总计<%= render_cart_total_price(current_cart) %> 元
        </span>
      </span>
    </div>

    <hr>

    <div class="checkout clearfix">
      <%= link_to("确认结账", checkout_carts_path, method: :post, class: "btn btn-lg btn-danger pull-right") %>
    </div>
  </div>