config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do
   resources :products
   resources :orders do
     member do
       post :cancel
       post :ship
       post :shipped
       post :return
     end
   end
  end

  resources :favorites

  resources :products do
    member do
      post :add_to_cart
      post :favorite
      post :unfavorite
    end
    collection do
     get :search
     get :fresh
     get :food
     get :men
     get :women
     get :beautiful
     get :glasses
     get :luggage
     get :furniture
   end
   resources :reviews
  end

  resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

   resources :cart_items do
     member do
       post :add_quantity
       post :remove_quantity
     end
   end

   resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

   namespace :account do
     resources :users
     resources :orders
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :reviews, dependent: :destroy
  has_many :favorites
  has_many :fans, :through => :favorites, :source => :user
  belongs_to :category

  has_many :photos
  accepts_nested_attributes_for :photos
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required

  def index
   @products = Product.all
  end

  def new
    @product = Product.new
    @categories = Category.all.map { |c| [c.name, c.id]}
    @photo = @product.photos.build
  end

  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]

    if @product.save
      if params[:photos] != nil
        params[:photos]['avatar'].each do |a|
          @photo = @product.photos.create(:avatar => a)
        end
      end
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
    @product = Product.find(params[:id])
    @product.category_id = params[:category_id]

    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end 


  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :company, :image, :category_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]

  def index
   @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
    current_cart.add_product_to_cart(@product)
    flash[:notice] = "你已成功将#{@product.title}加入购物车"
  else
    flash[:warning] = "你的购物车中已有此商品"
  end
    redirect_back fallback_location: root_path
  end

  def search
    if @query_string.present?
      search_result = Product.ransack(@search_criteria).result(:distinct => true)
      @products = search_result
    end
  end

   def fresh
    @products = Product.where(:category_id => 1)
   end

   def food
     @products = Product.where(:category_id => 2)
   end

   def men
     @products = Product.where(:category_id => 3)
   end

   def women
     @products = Product.where(:category_id => 4)
   end

   def beautiful
     @products = Product.where(:category_id => 5)
   end

   def glasses
     @products = Product.where(:category_id => 6)
   end

   def luggage
     @products = Product.where(:category_id => 7)
   end

   def furniture
     @products = Product.where(:category_id => 8)
   end

  def favorite
    @product = Product.find(params[:id])
    current_user.favorite_products << @product
    flash[:notice] = "您已收藏宝贝"
    redirect_back fallback_location: root_path
  end

  def unfavorite
    @product = Product.find(params[:id])
    current_user.favorite_products.delete(@product)
    flash[:notice] = "您已取消收藏宝贝"
    redirect_back fallback_location: root_path
  end

  protected  # 放在最后


  def validate_search_key
   @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
   @search_criteria = search_criteria(@query_string)
 end

 def search_criteria(query_string)
   { :title_cont => query_string }
 end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_highlight_content(product,query_string)
   excerpt_cont = excerpt(product.title, query_string, radius: 500)
   highlight(excerpt_cont, query_string)
 end

 def render_active(index)
  if index == 0
    "active"
  end
end 
end

app/views/admin/products/edit.html.erb
<h2 class="text-center">编辑商品</h2>
<div class="col-md-6 col-md-offset-3">
  <%= simple_form_for [:admin,@product] do |f| %>

  <%= f.input :title, :label => "产品名称"%>
  <%= f.input :company, :label => "企业名称"%>
  <%= f.input :description,:label => "产品描述" %>
  <%= f.input :quantity,:label => "产品数量" %>
  <%= f.input :price ,:label => "产品价格"%>
    <%= f.select :category_id, @categories , :prompt => "类别" %> <br><br>
  <% if @product.image.present? %>
    <span>目前商品图</span> <br>
    <%= image_tag(@product.image.thumb.url) %>
  <% end %>

  <div class="group">
    <%= f.input :image, as: :file %>
  </div>
  <%= f.submit "Submit", data: {disable_with: "Submitting..."}%>
  <% end %>
</div>

app/views/admin/products/index.html.erb
<h2 class="text-center"> 商品列表 </h2>
<div class="col-md-8 col-md-offset-2">
  <div class="pull-right" style="padding-bottom: 20px;">
    <%= link_to(" 管理订单", admin_orders_path, class: "btn btn-primary btn-sm" )%>
    <%= link_to("新增产品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th width="100">商品ID</th>
        <th >商品图片</th>
        <th width="220">名称</th>
        <th width="100">价格</th>
        <th width="150">操作选项</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td>
            <%= product.id %>
          </td>
          <td>
            <%= link_to product_path(product) do %>
              <% if product.photos.present? %>
              <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail") %>
              <% else %>
                <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= product.title %>
          </td>
          <td>
            <%= product.price %>
          </td>
          <td>
            <%= link_to("编辑", edit_admin_product_path(product), class: "btn btn-info btn-xs") %>
            <%= link_to("删除", admin_product_path(product),class: "btn btn-danger btn-xs", method: :delete, data: {confirm: "你确定要删除吗"})%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/products/new.html.erb
<h2 class="text-center">新增商品</h2>
<div class="col-md-6 col-md-offset-3">
  <%= simple_form_for [:admin,@product] do |f| %>

  <%= f.input :title, :label => "产品名称", :required => true%>
  <%= f.input :company, :label => "企业名称", :required => true%>
  <%= f.input :description,:label => "产品描述", :required => true %>
  <%= f.input :quantity,:label => "产品数量", :required => true %>
  <%= f.input :price ,:label => "产品价格", :required => true%>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "商品类别", :required => true)%> <br><br>
  <div class="group">
    <%= f.label :avatar,:label => "产品图片" %>
    <%= f.file_field :avatar, :multiple => true, name: "photos[avatar][]" %><br>
  </div>
  <%= f.submit "Submit", data: {disable_with: "Submitting..."}%>
  <% end %>
</div>