config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do
   resources :products
   resources :orders do
     member do
       post :cancel
       post :ship
       post :shipped
       post :return
     end
   end
  end

  resources :favorites

  resources :products do
    member do
      post :add_to_cart
      post :favorite
      post :unfavorite
    end
    collection do
     get :search
     get :fresh
     get :food
     get :men
     get :women
     get :beautiful
     get :glasses
     get :luggage
     get :furniture
   end
   resources :reviews
  end

  resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

   resources :cart_items do
     member do
       post :add_quantity
       post :remove_quantity
     end
   end

   resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

   namespace :account do
     resources :users
     resources :orders
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :reviews, dependent: :destroy
  has_many :favorites
  has_many :fans, :through => :favorites, :source => :user
  belongs_to :category

  has_many :photos
  accepts_nested_attributes_for :photos
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required

  def index
   @products = Product.all
  end

  def new
    @product = Product.new
    @categories = Category.all.map { |c| [c.name, c.id]}
    @photo = @product.photos.build
  end

  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]

    if @product.save
      if params[:photos] != nil
        params[:photos]['avatar'].each do |a|
          @photo = @product.photos.create(:avatar => a)
        end
      end
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
    @product = Product.find(params[:id])
    @product.category_id = params[:category_id]

    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end 


  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :company, :image, :category_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]

  def index
   @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
    current_cart.add_product_to_cart(@product)
    flash[:notice] = "你已成功将#{@product.title}加入购物车"
  else
    flash[:warning] = "你的购物车中已有此商品"
  end
    redirect_back fallback_location: root_path
  end

  def search
    if @query_string.present?
      search_result = Product.ransack(@search_criteria).result(:distinct => true)
      @products = search_result
    end
  end

   def fresh
    @products = Product.where(:category_id => 1)
   end

   def food
     @products = Product.where(:category_id => 2)
   end

   def men
     @products = Product.where(:category_id => 3)
   end

   def women
     @products = Product.where(:category_id => 4)
   end

   def beautiful
     @products = Product.where(:category_id => 5)
   end

   def glasses
     @products = Product.where(:category_id => 6)
   end

   def luggage
     @products = Product.where(:category_id => 7)
   end

   def furniture
     @products = Product.where(:category_id => 8)
   end

  def favorite
    @product = Product.find(params[:id])
    current_user.favorite_products << @product
    flash[:notice] = "您已收藏宝贝"
    redirect_back fallback_location: root_path
  end

  def unfavorite
    @product = Product.find(params[:id])
    current_user.favorite_products.delete(@product)
    flash[:notice] = "您已取消收藏宝贝"
    redirect_back fallback_location: root_path
  end

  protected  # 放在最后


  def validate_search_key
   @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
   @search_criteria = search_criteria(@query_string)
 end

 def search_criteria(query_string)
   { :title_cont => query_string }
 end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_highlight_content(product,query_string)
   excerpt_cont = excerpt(product.title, query_string, radius: 500)
   highlight(excerpt_cont, query_string)
 end

 def render_active(index)
  if index == 0
    "active"
  end
end 
end

app/views/products/_category_form.html.erb
<div class="product-box">
  <div class="product-box2">
    <% @products.each do |product| %>
      <div class="col-xs-6 col-sm-4 col-md-3">
        <div class="product-box3">
        <%= link_to product_path(product) do %>
          <% if product.photos.present? %>
            <%= image_tag(product.photos[0].avatar.thumb.url) %>
          <% else %>
            <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
          <% end %>
        <% end %>
        <div class="product-info">
          <p class="supplier"><%= product.company %></p>
          <p class="title"><%= product.title %></p> <!-- 商品名称 -->
          <p class="priceBox">
            <span>￥<%= product.price %></span>
            <span>爆品</span>
            <span>一起拼</span>
          </p> <!-- 商品价格 -->
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/products/beautiful.html.erb
<div class="category-title">
  <h3 class="text-center">全部美妆</h3>
</div>
<%= render "category_form"%>

app/views/products/books.html.erb
<div class="category-title">
  <h3 class="text-center">全部图书</h3>
</div>
<%= render "category_form"%>

app/views/products/computer.html.erb
<div class="category-title">
  <h3 class="text-center">全部电脑</h3>
</div>
<%= render "category_form"%>

app/views/products/food.html.erb
<div class="category-title">
  <h3 class="text-center">全部食品</h3>
</div>
<%= render "category_form"%>

app/views/products/fresh.html.erb
<div class="category-title">
  <h3 class="text-center">全部生鲜</h3>
</div>

<%= render "category_form"%>

app/views/products/furniture.html.erb
<div class="category-title">
  <h3 class="text-center">全部家居</h3>
</div>
<%= render "category_form"%>

app/views/products/glasses.html.erb
<div class="category-title">
  <h3 class="text-center">全部眼镜</h3>
</div>
<%= render "category_form"%>

app/views/products/index.html.erb
<div class="category-title">
  <h3 class="text-center">全部商品</h3>
</div>
<div class="product-box">
  <div class="product-box2">
    <% @products.each do |product| %>
      <div class="col-xs-8 col-sm-4 col-md-3">
        <div class="product-box3">
        <%= link_to product_path(product) do %>
          <% if product.photos.present? %>
            <%= image_tag(product.photos[0].avatar.thumb.url) %>
          <% else %>
            <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
          <% end %>
        <% end %>
        <div class="product-info">
          <p class="supplier"><%= product.company %> <span><%= product.category.name %></span></p>
          <p class="title"><%= product.title %></p> <!-- 商品名称 -->
          <p class="priceBox">
            <span>￥<%= product.price %></span>
            <span>爆品</span>
            <span>一起拼</span>

          </p> <!-- 商品价格 -->
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/products/luggage.html.erb
<div class="category-title">
  <h3 class="text-center">全部箱包</h3>
</div>
<%= render "category_form"%>

app/views/products/men.html.erb
<div class="category-title">
  <h3 class="text-center">全部男装</h3>
</div>
<%= render "category_form"%>

app/views/products/search.html.erb
<div class="col-md-6 col-md-offset-5">
  <br>
  <% if @query_string.blank? %>
    <div class="search-info-title">
      Sorry, The search content cannot be blank, pleace type some product into to search.
    </div>
    <% elsif @products.blank? %>
    <br>
    <h2 class="search-info-title"> 输入关键字，例如：苹果</h2>
  <% else %>
    <h2 class="search-info-title">有关"<%= @query_string %>"的信息</h2>
    <div class="search_result">
      <div class="row groups-show0"></div>
      <div class="group-table">
        <% @products.each do |product| %>
          <div class="row groups-show">
            <div class="col-md-12 col-lg-9 col-lg-offset-1">
              <p><%= link_to(render_highlight_content(product, @query_string),product_path(product)) %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>

  <% end %>
</div>

app/views/products/show.html.erb
<div class="product-show-box9">
  <div class="product-photos-box">
    <% if @photos.present? %>
   <div class="show-picture">
     <% @photos.each_with_index do |p,index| %>
       <% if index <1 %>
        <div class= "tab-pane <%= render_active(index) %>" id="<%= index %>"><%= image_tag (p.avatar.medium.url) %>
        </div>
       <% end %>
     <% end %>
   </div>
   <div class="show-photo-xsmall-box">
     <% @photos.each_with_index do |p,index| %>
       <% if index <5 %>
         <div class="small-product">
           <%= image_tag p.avatar.small.url%>
         </div>
       <% end %>
     <% end %>
   </div>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class:"thumbnail") %>
    <% end %>
  </div>


  <section class="product-main-box">
    <div class="title">
      <h1><%= @product.title %></h1>
    </div>
    <span class="description">
      <p><%= @product.company%></p>
    </span>
    <span class="description">
      <p><%= @product.category.name %></p>
    </span>

    <p class="xushu">
      <%= @product.description%>
    </p>
    <div class="price">
      <span>售价 :</span>
      <span>￥</span>
      <span><%= @product.price %></span>
      <span>数量 :</span>
      <span><%= @product.quantity %></span>
    </div>
    <hr/>
    <!-- 产品规格：尺寸 / 重量 / 材质 / 产地 / 备注-->
    <div class="specification">
      <ul class="fuwu">
        <li>品质保证</li>
        <li>先行赔付</li>
        <li>顺丰包邮</li>
        <li>闪电退款</li>
      </ul>
      <div class="fenxiang">
       <span>
           <% if current_user %>
            <% if !current_user.is_fan_of?(@product) %>
              <%= link_to favorite_product_path(@product), :class => "like btn btn-default", method: :post do %>
                <i class="fa fa-heart fa-lg"></i>
              <% end %>
            <% else %>
              <%= link_to unfavorite_product_path(@product), :class => "unlike btn btn-default", method: :post do %>
                <i class="fa fa-heart fa-lg"></i>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to favorite_product_path(@product), :class => "like btn btn-default",method: :post do %>
              <i class="fa fa-heart fa-lg"></i>
            <% end %>
          <% end %>
          <span> 收藏人气（<%= @product.fans.count %>）</span>
       </span>
       <span class="share">
         <span>分享:</span>
         <a href="#"><i class="fa fa-twitter"></i></a>
         <a href="#"><i class="fa fa-facebook"></i></a>
         <a href="#"><i class="fa fa-google"></i></a>
         <a href="#"><i class="fa fa-pinterest"></i></a>
         <a href="#"><i class="fa fa-wechat"></i></a>
       </span>
     </div>
    </div>
    <hr/>
    <div class="">
      <div class="pull-left">
          <% if @product.quantity > 0 %>
          <%= link_to("加入购物车", add_to_cart_product_path(@product), method: :post, class:"btn btn-lg btn-default") %>
          <% else %>
          已销售一空，无法购买
          <% end %>
      </div>

    </div>

    <br>
    <!-- 购买按钮 -->

  </section>
  <div style="clear: both;"></div>
  <!-- 评论 -->
    <div class="product-comment">
      <ul class="comment-head">
        <li role="presentation" class="active">
          <a href="#tab_default_1" data-toggle="tab">宝贝详情</a>
        </li>
        <li class="pingjia">
          <a href="#tab_default_2" data-toggle="tab">宝贝评价(<%= @product.reviews.count %>) </a>
        </li>
      </ul>
      <br />
      <div class="tab-content">
        <div class="tab-pane active" id="tab_default_1">
           <p class="product-description2 text-center">产品展示</p>
            <!--商品大图展示 -->
            <div class="product-image">
               <% @photos.each_with_index do |p,index| %>
                 <% if index <5 %>
                   <div class="small-product">
                     <%= image_tag p.avatar.url%>
                   </div>
                 <% end %>
               <% end %>
             </div>

             <p class="product-description2 text-center">常见问题</p>
           <div class="faq">
             <p class="question">顾客：请问包邮吗？</p>
             <p class="answer">包邮，默认使用顺丰快递发货，配送范围覆盖全国大部分地区（港澳台地区除外）。</p>
             <p class="question">顾客：如何申请退货？</p>
             <p class="answer">
               1.自签收之日起7日内，顾客可申请无忧退货，退款将原路返还，预计1-5个工作日到账；<br />
               2.退货流程：确认收货-申请退货-客服审核通过-用户寄回商品-仓库签收验货-退款审核-退款完成；<br />
               3.因客户个人原因产生的退货，购买和寄回运费由客户个人承担。<br />
             </p>
             <p class="question">顾客：如何开具发票？</p>
             <p class="answer">如需开具普通发票，请在下单时联系客服办理，我们将虽货物一起快递给您；</p>
           </div>
        </div><!-- End of tab_default_1 -->

       <div class="tab-pane comment-centent" id="tab_default_2">
         <p class="product-description2 text-center">商品评论</p>
            <div class="row">
              <div class="col-sm-12 ">
                <div >
                  <%= render @product.reviews%>
                  <%= render "reviews/form"%>
                </div>
              </div>
            </div>
          </div><!-- End of tab_default_2 -->
        </div><!-- End of tab-content -->
    </div>
    <div style="clear: both;"></div>
</div>

app/views/products/women.html.erb
<div class="category-title">
  <h3 class="text-center">全部女装</h3>
</div>
<%= render "category_form"%>