config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do
   resources :products
   resources :orders do
     member do
       post :cancel
       post :ship
       post :shipped
       post :return
     end
   end
  end

  resources :favorites

  resources :products do
    member do
      post :add_to_cart
      post :favorite
      post :unfavorite
    end
    collection do
     get :search
     get :fresh
     get :food
     get :men
     get :women
     get :beautiful
     get :glasses
     get :luggage
     get :furniture
   end
   resources :reviews
  end

  resources :carts do
     collection do
       delete :clean
       post :checkout
     end
   end

   resources :cart_items do
     member do
       post :add_quantity
       post :remove_quantity
     end
   end

   resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

   namespace :account do
     resources :users
     resources :orders
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
     ci = cart_items.build
     ci.product = product
     ci.quantity = 1
     ci.save
   end

   def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

  def clean!
   cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  has_many :product_lists

  def set_payment_with!(method)
     self.update_columns(payment_method: method )
   end

   def pay!
     self.update_columns(is_paid: true )
   end

   include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned


    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid,         to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :reviews, dependent: :destroy
  has_many :favorites
  has_many :fans, :through => :favorites, :source => :user
  belongs_to :category

  has_many :photos
  accepts_nested_attributes_for :photos
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/review.rb
class Review < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    is_admin
  end

  has_many :orders
  has_many :reviews, dependent: :destroy
  has_many :favorites
  has_many :favorite_products, :through => :favorites, :source => :product

  def is_fan_of?(group)
    favorite_products.include?(group)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
   :user
 end

 def resource
     @resource ||= User.new
 end

 def resource_class
     User
 end

 def devise_mapping
     @devise_mapping ||= Devise.mappings[:user]
 end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
     cart.total_price
   end 
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_paid_state(order)
   if order.is_paid?
     "已付款"
   else
     "未付款"
   end
 end
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_highlight_content(product,query_string)
   excerpt_cont = excerpt(product.title, query_string, radius: 500)
   highlight(excerpt_cont, query_string)
 end

 def render_active(index)
  if index == 0
    "active"
  end
end 
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<div class="row">
  <div class="footer1">
    <div class="wechat">
      <div class="wechat-lfet">
        <div class="wechat-image">
          <%= image_tag ("https://upload-images.jianshu.io/upload_images/12661863-98b7f44051923053.jpeg?imageMogr2/auto-orient/strip|imageView2/2/w/430/format/webp")%>
        </div>
        <ul class="wechat-info">
          <li>第九块购物网站，要你想要！</li>
          <li>随时随地掌握上新信息</li>
          <li>浏览、购买更便捷</li>
          <li>体验更多黑科技</li>
        </ul>
      </div>
      <div class="wechat-right">
        <div class="wechat-image">
          <%= image_tag ("https://upload-images.jianshu.io/upload_images/12661863-98b7f44051923053.jpeg?imageMogr2/auto-orient/strip|imageView2/2/w/430/format/webp")%>
        </div>
        <ul class="wechat-info">
          <li>
            扫码加我微信一起学习成长吧！
          </li>
          <li>
            <a href="https://github.com/zhaozongchang">我的GitHub</a>
          </li>

          <li>
            <a href="https://www.jianshu.com/u/88f7c9a90d6e">我的简书</a>
          </li>
          <li>
            我的邮箱：xingyingsuifeng@gmail.com
          </li>
          <li>我的电话：13188887761</li>
        </ul>
      </div>
    </div>
    </div>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" id="navbar" role="navigation">
  <div class="container-fluid col-md-8 col-md-offset-2">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <!-- <span class="sr-only">Toggle navigation</span> -->
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="/"><span><%= image_tag("https://upload-images.jianshu.io/upload_images/12661863-aaf5e2d95e4feaf0.png?imageMogr2/auto-orient/strip|imageView2/2/w/796/format/webp")%></span>第九块商城</a>
    </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav weishenme">
            <li class="quanbu">
              <%= link_to("全部商品", products_path)%>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-left">
             <%= form_tag search_products_path, :method => :get do %>
               <div class="input-group" id="search-id" >
                 <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="请输入搜索内容...">
                 <div class="input-group-btn">
                   <button class="btn btn-default" type="submit">
                     <i class="glyphicon glyphicon-search"></i>
                   </button>
                 </div>
               </div>
             <% end %>
           </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to carts_path do %>
                购物车 <i class="fa fa-shopping-cart"> </i> ( <%= current_cart.products.count %> )
                <% end %>
              </li>
              <% if !current_user %>
              <li><a href="#" data-toggle="modal" data-target="#signup-modal"><i class="fa fa-user-circle-o" aria-hidden="true"></i> 注册</a></li>
              <li>
                <a href="#" data-toggle="modal" data-target="#login-modal"><i class="fa fa-sign-in" aria-hidden="true"></i> 登入</a>
              </li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <i class="fa fa-user-circle" aria-hidden="true"> <%= current_user.email %></i>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <% if current_user.admin? %>
                      <li>
                        <%= link_to(" 管理商品", admin_products_path ,class: "fa fa-cogs" ) %>
                      </li>
                      <li class="divider"></li>
                      <li> <%= link_to(" 管理订单", admin_orders_path, class: "fa fa-credit-card-alt" )%> </li>
                      <% end %>
                      <li class="divider"></li>
                      <li>
                       <%= link_to(" 用户中心", edit_account_user_path(current_user),class:"fa fa-user") %>
                     </li>
                     <li class="divider"></li>
                      <li>
                        <%= link_to(" 个人订单",account_orders_path,class:"fa fa-id-card")%>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to(" 我的收藏", favorites_path, class: "fa fa-heart" ) %>
                      </li>
                      <li class="divider"></li>
                        <li> <%= link_to(content_tag(:i, ' 登  出 ', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<!-- 以下代码添加在最后 -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog" role="document">
    <div class="loginmodal-container">
       <h2 class="text-center">欢迎登入</h2>
       <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
         <div class="form-inputs">
           <%= f.input :email,label:"邮箱", required: false, autofocus: true %>
           <%= f.input :password,label:"密码", required: false %>
           <%= f.input :remember_me,label:"记住密码", as: :boolean if devise_mapping.rememberable? %>
         </div>
         <div class="form-actions">
           <%= f.button :submit, "登 入" %>
         </div>
       <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <h2 class="text-center">注册</h2>
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :email,label:"邮箱", required: true, autofocus: true %>
          <%= f.input :password,label:"密码", required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= f.input :password_confirmation,label:"确认密码", required: true %>
        </div>
        <div class="form-actions">
            <%= f.button :submit, "注 册" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JDstore 后台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "common/navbar" %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li> <%= link_to("Products", admin_products_path) %> </li>
          <li> <%= link_to("Orders", admin_orders_path) %> </li>
        </ul>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DJKstoreV5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link  href="favicon4.ico" rel="shortcut icon">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <%= render "common/navbar" %>
        <%= render "common/flashes" %>
      </div>
      <div class="row">
        <%= yield %>
      </div>
      <%= render "common/footer" %>
    </div>
  </body>
</html>